simplify pipeline and better linter

diff --git a/.github/workflows/main-ci.yaml b/.github/workflows/main-ci.yaml
--- a/.github/workflows/main-ci.yaml
+++ b/.github/workflows/main-ci.yaml
@@ -55,7 +55,11 @@ jobs:
       # Linting approfondi
       - name: Thorough Linting
         continue-on-error: true
-        run: devbox run lint-thorough
+        run: |
+          OUTPUT=$(devbox run lint-thorough 2>&1)
+          if [ $? -ne 0 ]; then
+            echo "::warning::🔍 Linting issues found:\n$OUTPUT"
+          fi
 
       # Tests unitaires
       - name: Run Tests
@@ -155,32 +159,32 @@ jobs:
     if: github.event_name == 'push' && github.ref == 'refs/heads/main'
     needs: [test, build]
 
-    steps:
-      - name: Cleanup old caches
-        uses: actions/github-script@v7
-        with:
-          script: |
-            // Use github.request to directly call the REST API endpoint for listing caches
-            const { data: cachesData } = await github.request('GET /repos/{owner}/{repo}/actions/caches', {
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-            });
+    # steps:
+    #   - name: Cleanup old caches
+    #     uses: actions/github-script@v7
+    #     with:
+    #       script: |
+    #         // Use github.request to directly call the REST API endpoint for listing caches
+    #         const { data: cachesData } = await github.request('GET /repos/{owner}/{repo}/actions/caches', {
+    #             owner: context.repo.owner,
+    #             repo: context.repo.repo,
+    #         });
 
-            // Extract the caches array from the response
-            const caches = cachesData.actions_caches;
+    #         // Extract the caches array from the response
+    #         const caches = cachesData.actions_caches;
 
-            // Garde seulement les 3 caches les plus récents
-            // Sort caches by creation date in descending order and keep only the first 5
-            const oldCaches = caches
-                .sort((a, b) => new Date(b.created_at) - new Date(a.created_at))
-                .slice(3); // Keep the first 3, so slice from index 5 onwards to get old caches
+    #         // Garde seulement les 3 caches les plus récents
+    #         // Sort caches by creation date in descending order and keep only the first 5
+    #         const oldCaches = caches
+    #             .sort((a, b) => new Date(b.created_at) - new Date(a.created_at))
+    #             .slice(3); // Keep the first 3, so slice from index 5 onwards to get old caches
 
-            for (const cache of oldCaches) {
-                console.log(`Deleting cache: ${cache.key} (ID: ${cache.id})`);
-                await github.rest.actions.deleteActionsCacheById({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                cache_id: cache.id,
-                });
-            }
-            console.log(`Deleted ${oldCaches.length} old caches.`);
+    #         for (const cache of oldCaches) {
+    #             console.log(`Deleting cache: ${cache.key} (ID: ${cache.id})`);
+    #             await github.rest.actions.deleteActionsCacheById({
+    #             owner: context.repo.owner,
+    #             repo: context.repo.repo,
+    #             cache_id: cache.id,
+    #             });
+    #         }
+    #         console.log(`Deleted ${oldCaches.length} old caches.`);
